name: Release for JitPack

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.2.0)'
        required: true
        type: string
      release_notes:
        description: 'Release notes'
        required: false
        type: string
        default: 'New release'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Update version in build.gradle.kts
        run: |
          # Remove -SNAPSHOT suffix and set the release version
          sed -i "s/version = \".*\"/version = \"${{ github.event.inputs.version }}\"/" build.gradle.kts
          
          # Show the updated version
          echo "Updated version to:"
          grep "^version = " build.gradle.kts
          
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          
      - name: Run tests
        run: ./gradlew test
        
      - name: Build JAR artifacts
        run: |
          ./gradlew jar
          ./gradlew androidJar
          ./gradlew jvmJar
          ./gradlew sourcesJar
          ./gradlew javadocJar
          
      - name: List built artifacts
        run: |
          echo "Built artifacts:"
          ls -la build/libs/
          
      - name: Create Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "${{ github.event.inputs.version }}" -m "Release ${{ github.event.inputs.version }}"
          git push origin "${{ github.event.inputs.version }}"
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: |
            ## Release ${{ github.event.inputs.version }}
            
            ${{ github.event.inputs.release_notes }}
            
            ### JitPack Usage
            
            Add JitPack repository to your build.gradle:
            ```gradle
            repositories {
                maven { url 'https://jitpack.io' }
            }
            ```
            
            Add dependency:
            ```gradle
            dependencies {
                implementation 'com.github.unicitynetwork:java-state-transition-sdk:${{ github.event.inputs.version }}'
            }
            ```
            
            ### Assets
            - Main JAR: `java-state-transition-sdk-${{ github.event.inputs.version }}.jar`
            - Android JAR: `java-state-transition-sdk-${{ github.event.inputs.version }}-android.jar`
            - JVM JAR: `java-state-transition-sdk-${{ github.event.inputs.version }}-jvm.jar`
            - Sources: `java-state-transition-sdk-${{ github.event.inputs.version }}-sources.jar`
            - Javadoc: `java-state-transition-sdk-${{ github.event.inputs.version }}-javadoc.jar`
          files: |
            build/libs/*.jar
          draft: false
          prerelease: false